Implemented Standalone App
jacobmillsfl/trainingwheels-bot pull request #26
Opened 2023-02-19 21:51 UTC by jacobmillsfl

- Standalone app now fully functional
- Underlying CommandUtil routines implemented

2023-02-19 21:58 UTC, JakeTompkins commented on src/utils/command_interface.py
> +        claimed_user = self.database.table_leetcodeuser_load_by_discord_id(leetcode_id)
Looks like you mean to use the by_leetcode_id method

2023-02-19 23:34 UTC, jacobmillsfl commented on src/utils/command_interface.py
> +            result = f"* * * CHALLANGE {latest['id']} | {start_date.date()} * * *\n\n"
Typo in CHALLENGE

2023-02-20 01:56 UTC, JakeTompkins requested changes

2023-02-20 01:56 UTC, JakeTompkins commented on src/utils/command_interface.py
> +            result = f"* * * CHALLANGE {latest['id']} | {start_date.date()} * * *\n\n"
```suggestion
            result = f"* * * CHALLENGE {latest['id']} | {start_date.date()} * * *\n\n"
```

2023-02-20 01:56 UTC, JakeTompkins commented on src/utils/command_interface.py
> +            result += "Leetcode user not found. Claim your user idea with"
```suggestion
            result += "Leetcode user not found. Claim your user id with"
```

2023-02-20 04:25 UTC, lcollins11 approved these changes

2023-02-20 04:26 UTC, JakeTompkins approved these changes

2023-02-20 04:26 UTC, merged